// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {port} from '../models';
import {process} from '../models';
import {main} from '../models';

export function AppName():Promise<string>;

export function GetPortList():Promise<Array<port.Info>>;

export function GetProcessList():Promise<Array<process.Info>>;

export function GetSystemResourceInfo():Promise<main.SystemResourceInfo>;
