// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddCustomProtectedProcessName(arg1) {
  return window['go']['main']['App']['AddCustomProtectedProcessName'](arg1);
}

export function AppName() {
  return window['go']['main']['App']['AppName']();
}

export function DeleteCustomProtectedProcessName(arg1) {
  return window['go']['main']['App']['DeleteCustomProtectedProcessName'](arg1);
}

export function GetOperationLogs() {
  return window['go']['main']['App']['GetOperationLogs']();
}

export function GetPortList() {
  return window['go']['main']['App']['GetPortList']();
}

export function GetProcessDetail(arg1) {
  return window['go']['main']['App']['GetProcessDetail'](arg1);
}

export function GetProcessList() {
  return window['go']['main']['App']['GetProcessList']();
}

export function GetProtectionSettings() {
  return window['go']['main']['App']['GetProtectionSettings']();
}

export function GetSystemResourceInfo() {
  return window['go']['main']['App']['GetSystemResourceInfo']();
}

export function KillProcessByPID(arg1) {
  return window['go']['main']['App']['KillProcessByPID'](arg1);
}

export function KillProcessByPort(arg1, arg2) {
  return window['go']['main']['App']['KillProcessByPort'](arg1, arg2);
}
