// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AppName() {
  return window['go']['main']['App']['AppName']();
}

export function GetPortList() {
  return window['go']['main']['App']['GetPortList']();
}

export function GetProcessList() {
  return window['go']['main']['App']['GetProcessList']();
}

export function GetSystemResourceInfo() {
  return window['go']['main']['App']['GetSystemResourceInfo']();
}
