// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {config} from '../models';
import {port} from '../models';
import {detail} from '../models';
import {process} from '../models';
import {main} from '../models';

export function AddCleanupRule(arg1:config.CleanupRuleInput):Promise<Array<config.CleanupRule>>;

export function AddCustomProtectedProcessName(arg1:string):Promise<config.ProtectionSettings>;

export function AppName():Promise<string>;

export function DeleteCleanupRule(arg1:string):Promise<Array<config.CleanupRule>>;

export function DeleteCustomProtectedProcessName(arg1:string):Promise<config.ProtectionSettings>;

export function GetCleanupRules():Promise<Array<config.CleanupRule>>;

export function GetOperationLogs():Promise<Array<config.OperationLog>>;

export function GetPortList():Promise<Array<port.Info>>;

export function GetProcessDetail(arg1:number):Promise<detail.ProcessDetail>;

export function GetProcessList():Promise<Array<process.Info>>;

export function GetProtectionSettings():Promise<config.ProtectionSettings>;

export function GetRecentOperationLogsForResource(arg1:number,arg2:string,arg3:Array<number>):Promise<Array<config.OperationLog>>;

export function GetSystemResourceInfo():Promise<main.SystemResourceInfo>;

export function KillProcessByPID(arg1:number):Promise<process.OperationResult>;

export function KillProcessByPort(arg1:number,arg2:string):Promise<process.OperationResult>;

export function SetCleanupRuleEnabled(arg1:string,arg2:boolean):Promise<Array<config.CleanupRule>>;
